name: Minecraft Mod

on:
  push: 
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
       gradle-version: '8.14.1'

    - name: Build jar
      run: gradle build

    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: Player-Miku
        path: build/PlayerMiku-*.*
